{% set name = "compact-json" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compact_json-{{ version }}.tar.gz
  sha256: 1dfcd53a05e27725fd73d694028c6d9a4b5e7fe8586d0980d0f7d5b5672ee144

build:
  entry_points:
    - compact-json=compact_json._compact_json:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.9,<4.0
  run:
    - wcwidth >=0.2.5,<=0.2.8
    - python >=3.9,<4.0
    - setuptools >=69.0.3
    - importlib-resources >=6.1

test:
  imports:
    - compact_json
  commands:
    - pip check
    - compact-json --help
  requires:
    - pip

about:
  home: https://github.com/masaccio/compact-json
  summary: A JSON formatter that produces compact but human-readable
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - thewchan
