{% set name = "compact-json" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compact_json-{{ version }}.tar.gz
  sha256: f981a149c4c1b874aa0204368fbeacec698d32ae3a93f016973e9f8ab8a85c59

build:
  entry_points:
    - compact-json=compact_json._compact_json:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.8,<4.0
  run:
    - wcwidth >=0.2.5,<0.3.0
    - python >=3.8,<4.0

test:
  imports:
    - compact_json
  commands:
    - pip check
    - compact-json --help
  requires:
    - pip

about:
  home: https://github.com/masaccio/compact-json
  summary: A JSON formatter that produces compact but human-readable
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - thewchan
